= trends.tf

Source code for https://trends.tf/[trends.tf]

== Getting started

=== Setting up a database

First, set up the database. Install postgresql and
https://www.postgresql.org/docs/current/app-initdb.html[initialize the cluster], if that wasn't done
automatically. You may also need to start the database by running

    $ sudo systemctl start postgresql

Next, create a postgres user for yourself

    $ sudo -u postgres createuser --interactive $USER

And then create a database owned by your user

    $ sudo -u postgres createdb -O $USER trends

Verify that you can connect to the database by running

    $ psql -d trends

You can exit the `psql` shell using the `\q` command.

=== Importing data

Create a virtualenv and activate it

    $ virtualenv venv
    $ source venv/bin/activate

Install trends.tf inside that virtualenv

    $ ./setup.py develop

There are several different ways to import new logs. To import the 1000 most recent logs from
https://logs.tf/[logs.tf], 

    $ trends_importer -vv logs bulk -c 1000 postgresql:///trends

Any valid https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING[connection
string] may be used instead of `postgresql:///trends`. To import logs continuously, remove the
`-c 1000` parameters.

The performance of trends.tf changes significantly as more data is imported into the database. To
quickly import many logs for testing, you can use the output of the
https://github.com/ldesgoui/clone_logs[`clone_logs` tool]. Cloned logs in batches of 100,000 are
available from https://mega.nz/#F!l9oGiKCb!lTWT2RSkTYv-TJZb92_ksA[Lucas Desgouilles's archive].  For
example, to import logs from the file `2200k-to-2300k.7z`, run

    $ 7z x 2200k-to-2300k.7z
    $ trends_importer -vv logs clone_logs -d 22.sqlite3 postgresql:///trends

To import recent player names and avatars, you will need a
https://steamcommunity.com/dev/apikey[Steam API key]. Then, to import the avatars and usernames for
all players currently in your database, run

    $ trends_importer players -k <steam API key> postgresql:///trends

replacing `<steam API key>` with your actual key.

=== Running the server

To launch a development server, run

    $ FLASK_ENV=development python -m trends.site

If you are using a different database, you will need to set the `DATABASE` environmental variable to
its connection string.

== Deploying trends.tf

These are the instructions to deploy a new server hosting trends.tf. The only requirements are that
it be running Arch Linux or Debian (Ubuntu will also likely work), and that there is ssh access
available (for the root user).

First, edit `salt/roster` to contain a new entry like

[source,yaml]
----
<name>:
  host: <ipaddr>
  user: root
----

Where `<name>` is the name you will use to refer to the server in the upcoming commands, and
`<ipaddr>` is the IP address of the server. Then, run

    $ salt-ssh -i <name> test.ping

The `-i` option will accept the server's host SSH key. You should see a response like

    <name>:
        True

The next few steps will create a user with ssh access and sudoer privileges. Create a link to the
ssh key you wish to install:

    $ ln -s ~/.ssh/id_rsa.pub salt/

You will need to do the same thing for ca.crt if you want to access netdata. Then, run

    $ salt-ssh <name> state.apply bootstrap

The output of this command should show all changes made to the server. Next, switch to using the
`sean` user to connect to the server. Modify the entry you previously made in `salt/roster` to be

[source,yaml]
----
<name>:
  host: <ipaddr>
  user: sean
  sudo: True
----

Then, run

    $ salt-ssh <name> state.apply

This will take a while (around 2 minutes). Once it is done, all states should have succeeded except
for `nginx.service` and `player_import.service`. This is because the certificates are missing and
the steamkey has not been set. To fix the first problem, copy over the certificates from an existing
site. That is, run

    [server1]$ sudo tar -cvf /tmp/certs.tar.gz /etc/letsencrypt/
    $ scp <server1>:/tmp/certs.tar.gz <server2>:/tmp/
    [server2]$ sudo tar -xvf /tmp/certs.tar.gz -C /

I would like to fix this at some point. Then, create a file `/etc/default/trends` containing

----
STEAMKEY=<steam API key>
----

with your https://steamcommunity.com/dev/apikey[Steam API key]. This really should be read from
pillar. Once this is complete, re-apply the top-level state.

    $ salt-ssh <name> state.apply
