name: Run test suite

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sudo mkdir -p /etc/postgresql-common/createcluster.d/
          echo "create_main_cluster = false" | \
            sudo tee /etc/postgresql-common/createcluster.d/override.conf
          sudo apt-get update
          sudo apt-get install -y python3-dev postgresql
          pip install -r requirements.txt -r requirements_test.txt
      - run: pytest
